services:
  web:
    build: .
    environment:
      MYENV: venv
    volumes:
      - .:/drf_firebase
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py customsuperuser
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
